# Generated by Django 3.2.16 on 2025-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250318_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
