# Generated by Django 3.2.16 on 2025-03-28 21:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('only_author_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
